<?php
session_start();
define('DB_SERVER','localhost');
define('DB_USER','root');
define('DB_PASS' ,'');
define('DB_NAME', 'covidtest.trusthospital');

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
class DB_con
{
  // public static $con;
 function __construct()
 {
$con = mysqli_connect(DB_SERVER,DB_USER,DB_PASS,DB_NAME);
$this->dbh=$con;
// Check connection
if (mysqli_connect_errno())
{
echo "Failed to connect to MySQL: " . mysqli_connect_error();
 }
 }
 public function fetchdata($start_from, $limit)
 {
 $myQuery = "SELECT * FROM products ORDER BY created_at DESC LIMIT $start_from, $limit";
 $result=mysqli_query($this->dbh, $myQuery);
 return $result;
 }
 public function countdata()
 {
 $myQuery = "SELECT * FROM products";
 $result=mysqli_query($this->dbh, $myQuery);
 $num = mysqli_num_rows($result);
 return $num;
 }
}


class dbData extends DB_con{
  public $id;

//   public function __construct($cat_id){
//   $this -> id = $cat_id;
// }


public function getPatientInfoForQRCode($reg_num)
{
   $myQuery = "SELECT * FROM patientbookingform WHERE registration_number = '$reg_num'";
   $result=mysqli_query($this->dbh, $myQuery);

}


  public function adminLogin($admin_email, $admin_pass){
     $encrypted_pass = md5($admin_pass);
    $myQuery = "SELECT * FROM user WHERE admin_email = '$admin_email' AND admin_pass = '$encrypted_pass'";
    $result=mysqli_query($this->dbh, $myQuery);
   //  return $result;
    $num = mysqli_num_rows($result);
    if($num == 1)
    {
      return $result;
    }elseif($num < 1)
    {
       return 'not found';
    }else
    {
      return 'error';
    }
    
  }

  public function searchPatient($reg_num){
  $myQuery = "SELECT * FROM patientbookingform WHERE registration_number = '$reg_num'";
  $result=mysqli_query($this->dbh, $myQuery);
//   return $reg_num;
//   die();
  $num = mysqli_num_rows($result);
  if($num == 1)
  {
    return $result;
  }elseif($num < 1){
     echo 'not found';
  }else{
   echo 'error';
  }
  
}

public function checkDataNum($reg_num){
   $myQuery = "SELECT * FROM patientbookingform WHERE registration_number = '$reg_num'";
   $result=mysqli_query($this->dbh, $myQuery);
   $num = mysqli_num_rows($result);
    return $num;
 }

  public function checkLogin($admin_email, $admin_pass){
   $encrypted_pass = md5($admin_pass);
  $myQuery = "SELECT * FROM user WHERE admin_email = '$admin_email' AND admin_pass = '$encrypted_pass'";
  $result=mysqli_query($this->dbh, $myQuery);
  $num = mysqli_num_rows($result);
   return $num;
  
}

  function callSmsAPI($method, $url, $data){
    $curl = curl_init();
    switch ($method){
       case "POST":
          curl_setopt($curl, CURLOPT_POST, 1);
          if ($data)
             curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
          break;
       case "PUT":
          curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "PUT");
          if ($data)
             curl_setopt($curl, CURLOPT_POSTFIELDS, $data);			 					
          break;
       default:
          if ($data)
             $url = sprintf("%s?%s", $url, http_build_query($data));
    }
    // OPTIONS:
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_HTTPHEADER, array(
       'APIKEY: 111111111111111111111',
       'Content-Type: application/json',
    ));
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    // EXECUTE:
    $result = curl_exec($curl);
    if(!$result){die("Connection Failure");}
    curl_close($curl);
    return $result;
 }


 function sendEmail($email, $name, $msg){
  
  
  //PHPMailer Object
  $mail = new PHPMailer(true); //Argument true in constructor enables exceptions
  
  
  
  $mail->isSMTP();
  $mail->Host = 'covidtest.thetrusthospital.com';
  $mail->SMTPAuth = true;
  $mail->Username = 'testcovid@covidtest.thetrusthospital.com'; //paste one generated by Mailtrap
  $mail->Password = 'testcovid12345'; //paste one generated by Mailtrap
  $mail->SMTPSecure = 'ssl';
  $mail->Port = 465;
  
  
  //From email address and name
  $mail->From = "testcovid@covidtest.thetrusthospital.com";
  $mail->FromName = "Covid Test Portal - The Trust Hospital";
  
  //To address and name
  $mail->addAddress($email, $name);
  // $mail->addAddress("menniablaise@hotmail.com");
  
  //Address to which recipient will reply
  // $mail->addReplyTo("menniablaise@yahoo.com", "Reply");
  
  //CC and BCC
  // $mail->addCC("cc@example.com");
  // $mail->addBCC("bcc@example.com");
  
  //Send HTML or Plain Text email
  $mail->isHTML(true);
  
  $mail->Subject = "Subject Text";
  $mail->Body = $msg;
  // $mail->AltBody = "This is the plain text version of the email content";
      if($mail->send())
      {
         return 'Loading...';
      }else{
         echo "Mailer Error: " . $mail->ErrorInfo;
      }
 }
}
